---
# install packages
- name: install packages
  yum: pkg={{ item }} state=installed
  with_items:
    - '@kde-desktop-environment'
    - GitPython
    - NetworkManager-openswan
    - NetworkManager-openvpn
    - NetworkManager-pptp
    - NetworkManager-vpnc
    - VirtualBox
    - ansible
    - bpython
    - colordiff
    - ctags
    - ctags-etags
    - dnspython
    - docker-io
    - dos2unix
    - dvdstyler
    - emacs
    - emacs-el
    - emacs-git
    - emacs-git-el
    - emacs-gnuplut
    - emacs-golang
    - emacs-goodies
    - emacs-mmm
    - emacs-mmm-el
    - emacs-pymacs
    - emacs-pymacs-el
    - euca2ools
    - fedora-packager
    - fedora-review
    - fedora-review-tests
    - fedpkg
    - git
    - gnupg
    - gnupg2
    - gnuplot
    - gnuplot-doc
    - gnuplot-py
    - golang
    - graphviz
    - gstreamer
    - gstreamer-plugins-bad-free
    - gstreamer-plugins-base
    - gstreamer-plugins-good
    - gstreamer-plugins-ugly
    - gstreamer1
    - gstreamer1-plugins-bad-free
    - gstreamer1-plugins-base
    - gstreamer1-plugins-good
    - gstreamer1-plugins-ugly
    - inkscape
    - ipset
    - k3b
    - koji
    - konversation
    - kpartx
    - libreoffice-calc
    - libreoffice-impress
    - libreoffice-math
    - libreoffice-writer
    - liveusb-creator
    - lm_sensors
    - lsof
    - man-pages
    - mercurial
    - mock
    - mod_ssl
    - mod_wsgi
    - mongodb
    - mongodb-server
    - mrtg
    - nmap
    - nmap-ncat
    - ntp
    - ntpdate
    - okular
    - pychecker
    - pyflakes
    - pylint
    - pyparsing
    - python-coverage
    - python-docker-py
    - python-lxml
    - python-mock
    - python-nose
    - python-pep8
    - python-pip
    - python-rope
    - python-ropemacs
    - python-ropemode
    - python-setuptools
    - python-tox
    - python-virtualenv
    - python-virtualenv
    - python-virtualenvwrapper
    - python3-bpython
    - recordmydesktop
    - rpm-build
    - rpm-python
    - rpmdevtools
    - rsync
    - screen
    - strace
    - subversion
    - sysstat
    - texlive
    - tito
    - vlc
    - wget
    - wireshark
    - xmlstarlet
    - zsh
- name: check for Vagrant RPM
  shell: rpm -q vagrant
  register: vagrant_installed_check
  ignore_errors: true
  changed_when: "vagrant_installed_check.rc != 0"
- name: install Vagrant
  shell: yum localinstall --nogpgcheck https://dl.bintray.com/mitchellh/vagrant/#vagrant_1.6.2_x86_64.rpm
  when: vagrant_installed_check.rc != 0
