---
# set up yum repos
- name: check for RPMFusion free
  shell: rpm -q rpmfusion-free-release
  register: rpmfusion_free_check
  ignore_errors: true
  changed_when: "rpmfusion_free_check.rc != 0"
- name: check for RPMFusion nonfree
  shell: rpm -q rpmfusion-nonfree-release
  register: rpmfusion_nonfree_check
  ignore_errors: true
  changed_when: "rpmfusion_nonfree_check.rc != 0"
- name: check for Adobe Flash repo
  shell: rpm -q adobe-release-x86_64
  register: adobe_release_check
  ignore_errors: true
  changed_when: "adobe_release_check.rc != 0"
- name: check for Nux Dextop repo
  shell: rpm -q nux-dextop-release
  register: nux_dextop_check
  ignore_errors: true
  changed_when: "nux_dextop_check.rc != 0"
- name: check for Virtualbox repo
  stat: path=/etc/yum.repos.d/virtualbox.repo follow=true
  register: virtualbox_repo_check

- name: install RPMFusion free release RPM
  shell: yum -y localinstall --nogpgcheck http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm
  when: rpmfusion_free_check.rc != 0 and ansible_os_family == "Fedora"
  notify:
    - yum clean all
- name: install RPMFusion nonfree release RPM
  shell: yum -y localinstall --nogpgcheck http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
  when: rpmfusion_nonfree_check.rc != 0 and ansible_os_family == "Fedora"
  notify:
    - yum clean all
- name: install Adobe release RPM
  command: yum -y localinstall --nogpgcheck http://linuxdownload.adobe.com/adobe-release/adobe-release-x86_64-1.0-1.noarch.rpm
  when: adobe_release_check.rc != 0
  notify:
    - yum clean all
- name: install Nux Dextop release RPM
  shell: yum -y localinstall --nogpgcheck http://li.nux.ro/download/nux/dextop/el7/x86_64/nux-dextop-release-0-1.el7.nux.noarch.rpm
  when: nux_dextop_check.rc != 0 and ansible_os_family == "RedHat"
- name: install VirtualBox yum repo
  get_url: url="http://download.virtualbox.org/virtualbox/rpm/{% if ansible_os_family == "Fedora" %}fedora{% else %}el{% endif %}/virtualbox.repo"
       dest="/etc/yum.repos.d" mode=0644
  when: virtualbox_repo_check.stat.exists == False
  notify:
    - yum clean all
