---
# set up users
- name: create fuse group
  group: name=fuse
- name: set up user account for {{ user }}
  user: >
    name={{ user }} state=present home=/home/{{ user }} uid={{ uid }}
    groups=mock,wheel,fuse,wireshark,vboxusers append=yes shell=/bin/zsh
    comment="Chris St. Pierre"
- name: set up sudoers
  copy: src=sudoers dest=/etc/sudoers mode=0400 owner=root group=root
